[[OpenSSL_CLI]]
arch = "aarch64"
git-tree-sha1 = "96c677d979a23acc602919dcd3c006620da1c946"
os = "macos"

    [[OpenSSL_CLI.download]]
    sha256 = "46bbe9f0f9f37437d1f198a05ab5f7530cec7b585c47389779d7099319a1fee6"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.7+0/OpenSSL_CLI.v3.5.7.aarch64-apple-darwin.tar.gz"
[[OpenSSL_CLI]]
arch = "aarch64"
git-tree-sha1 = "fcbf7b57eb4e5e557cbfdc57a7dc4ffe289fe108"
libc = "glibc"
os = "linux"

    [[OpenSSL_CLI.download]]
    sha256 = "6aa7d4bd7ddb4baa64cdee0b58315d4f7762068d1125a377232d112f1b4f004d"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.7+0/OpenSSL_CLI.v3.5.7.aarch64-linux-gnu.tar.gz"
[[OpenSSL_CLI]]
arch = "aarch64"
git-tree-sha1 = "3d01f9a5b91e4908292175abc6f1869a7830a194"
libc = "musl"
os = "linux"

    [[OpenSSL_CLI.download]]
    sha256 = "848bccc73cf5ffb43db8c951e9565df79b6e38ed27bc04b9f2a767262ec9c6e5"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.7+0/OpenSSL_CLI.v3.5.7.aarch64-linux-musl.tar.gz"
[[OpenSSL_CLI]]
arch = "aarch64"
git-tree-sha1 = "794787386681ba07e344e38c84e7a45bb472a524"
os = "freebsd"

    [[OpenSSL_CLI.download]]
    sha256 = "02523139b62333b0fc18798dd59f10b2d9fd3a266d126e210014967bd4f50d22"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.7+0/OpenSSL_CLI.v3.5.7.aarch64-unknown-freebsd.tar.gz"
[[OpenSSL_CLI]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "21e46beabfea03136ce3ed34b09268bb46a7cf52"
libc = "glibc"
os = "linux"

    [[OpenSSL_CLI.download]]
    sha256 = "66ef670438e63b6853a0bf641fa27ca6b869e16be293edbadcdbe688a5475c4d"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.7+0/OpenSSL_CLI.v3.5.7.armv6l-linux-gnueabihf.tar.gz"
[[OpenSSL_CLI]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0928e78ebb99b0b371823175478df2acad9ef116"
libc = "musl"
os = "linux"

    [[OpenSSL_CLI.download]]
    sha256 = "20dd124d00623d7b3e9b8eecf43eeb9a2f61fabdb2981d1686e23051f1dc4906"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.7+0/OpenSSL_CLI.v3.5.7.armv6l-linux-musleabihf.tar.gz"
[[OpenSSL_CLI]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "493da1e5296f80836ab4a02f9aabb172401c46c0"
libc = "glibc"
os = "linux"

    [[OpenSSL_CLI.download]]
    sha256 = "c3ade07ebc17d98a29c57d47ce6aa98fe5d5b3ff9b0c58584329e068084880bf"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.7+0/OpenSSL_CLI.v3.5.7.armv7l-linux-gnueabihf.tar.gz"
[[OpenSSL_CLI]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fafa420d857b1ec9e7a83d53404b52989a96adda"
libc = "musl"
os = "linux"

    [[OpenSSL_CLI.download]]
    sha256 = "9a60d803b665c99ceddfb4f5ff2455f07e235959da45216d166cb436acc3c010"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.7+0/OpenSSL_CLI.v3.5.7.armv7l-linux-musleabihf.tar.gz"
[[OpenSSL_CLI]]
arch = "i686"
git-tree-sha1 = "77e5344d74abacc27ab9ea7800c95304ffb6963d"
libc = "glibc"
os = "linux"

    [[OpenSSL_CLI.download]]
    sha256 = "f98c2800fede0043464de9560bfa04d3f6a806abc303603384a8af4884a0f43d"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.7+0/OpenSSL_CLI.v3.5.7.i686-linux-gnu.tar.gz"
[[OpenSSL_CLI]]
arch = "i686"
git-tree-sha1 = "26d7b8f48ebb3a2c0df924e30ee3950f67ee8aa0"
libc = "musl"
os = "linux"

    [[OpenSSL_CLI.download]]
    sha256 = "944970e82b72c3ca07f170bf7b2f8299624f613eb8d01b4c5ea8d9ebb67b8f96"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.7+0/OpenSSL_CLI.v3.5.7.i686-linux-musl.tar.gz"
[[OpenSSL_CLI]]
arch = "i686"
git-tree-sha1 = "7560300a2c5ee7adaf8619d7af44b5151372bd5c"
os = "windows"

    [[OpenSSL_CLI.download]]
    sha256 = "3f5ba49c59c7f30ea5e4976f7eae0338e1a40ba05e89a350666fa22e6e39988e"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.7+0/OpenSSL_CLI.v3.5.7.i686-w64-mingw32.tar.gz"
[[OpenSSL_CLI]]
arch = "powerpc64le"
git-tree-sha1 = "b56b74b29eb594d59c5fe2561be8858b939c6fcf"
libc = "glibc"
os = "linux"

    [[OpenSSL_CLI.download]]
    sha256 = "4171fb96f02ed4b92ec78f5daa7becdfaca1115fe1861ddb7b8d4c3f477bae3d"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.7+0/OpenSSL_CLI.v3.5.7.powerpc64le-linux-gnu.tar.gz"
[[OpenSSL_CLI]]
arch = "riscv64"
git-tree-sha1 = "730729ef55a314d04f0f33e2c0c3b31e62a4124f"
libc = "glibc"
os = "linux"

    [[OpenSSL_CLI.download]]
    sha256 = "08330ec6ff59e3a57b6aa806f5a1ca6c6406ff235c5d60cec3c61af382052bed"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.7+0/OpenSSL_CLI.v3.5.7.riscv64-linux-gnu.tar.gz"
[[OpenSSL_CLI]]
arch = "x86_64"
git-tree-sha1 = "58580a1baf2a2c039f92761c11a0a46bfa55f48a"
os = "macos"

    [[OpenSSL_CLI.download]]
    sha256 = "014aba9a99c7e85539fb70dbe3bae849520a72433b0085a56dc8874b1da003c5"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.7+0/OpenSSL_CLI.v3.5.7.x86_64-apple-darwin.tar.gz"
[[OpenSSL_CLI]]
arch = "x86_64"
git-tree-sha1 = "a2b830722d6f9d7fe16ba3736160251bbec3b55d"
libc = "glibc"
os = "linux"

    [[OpenSSL_CLI.download]]
    sha256 = "4a294e4906446d83ae21b077e725d4bf212f8946115fde637bd18c57baf815d7"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.7+0/OpenSSL_CLI.v3.5.7.x86_64-linux-gnu.tar.gz"
[[OpenSSL_CLI]]
arch = "x86_64"
git-tree-sha1 = "051b18b410233d4bcfa994d6fdca8bb466486272"
libc = "musl"
os = "linux"

    [[OpenSSL_CLI.download]]
    sha256 = "c4e7e391ae0ea88789e536aa85ef8beeb6610f06ec2642ca14fe55eeb22c742b"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.7+0/OpenSSL_CLI.v3.5.7.x86_64-linux-musl.tar.gz"
[[OpenSSL_CLI]]
arch = "x86_64"
git-tree-sha1 = "a3f8d75ebb45d6a9fe34bd300c07e2d45c2fa19c"
os = "freebsd"

    [[OpenSSL_CLI.download]]
    sha256 = "173579544e1cecba357042b32d2ecc3ff2f0a7a4fdd37b47beb06af93a346f49"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.7+0/OpenSSL_CLI.v3.5.7.x86_64-unknown-freebsd.tar.gz"
[[OpenSSL_CLI]]
arch = "x86_64"
git-tree-sha1 = "f3344350ddf95b084c18ffd275613168689a6826"
os = "windows"

    [[OpenSSL_CLI.download]]
    sha256 = "f6c84d58fac4e726c7e0a3f0773b15364b93c0f44b62c2e4ebbcceb135d95419"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.7+0/OpenSSL_CLI.v3.5.7.x86_64-w64-mingw32.tar.gz"
