[[OpenSSL_CLI]]
arch = "aarch64"
git-tree-sha1 = "d2689ce87a0c5753e831c2867618d6136390dcee"
os = "macos"

    [[OpenSSL_CLI.download]]
    sha256 = "b012d20aa972c8d4f4fdec411756f845e9c2dfd34f100fcb4bd235f98d13176a"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.8+0/OpenSSL_CLI.v3.5.8.aarch64-apple-darwin.tar.gz"
[[OpenSSL_CLI]]
arch = "aarch64"
git-tree-sha1 = "2090af63c44ecd5aa22961e2df4143e984d5f93a"
libc = "glibc"
os = "linux"

    [[OpenSSL_CLI.download]]
    sha256 = "f637dbc98e4819d6142d1befc2745c61b208b35d4567593e6d0e76696474404b"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.8+0/OpenSSL_CLI.v3.5.8.aarch64-linux-gnu.tar.gz"
[[OpenSSL_CLI]]
arch = "aarch64"
git-tree-sha1 = "62833415e66d5c60f5b178af6e43a7cf3608a962"
libc = "musl"
os = "linux"

    [[OpenSSL_CLI.download]]
    sha256 = "7e231851b63c005759fc6b01f14259ed7afeabfa2f028b23dcecdb54375b76e4"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.8+0/OpenSSL_CLI.v3.5.8.aarch64-linux-musl.tar.gz"
[[OpenSSL_CLI]]
arch = "aarch64"
git-tree-sha1 = "822032faca4fd3064a9b829108fb44ab728b3e9c"
os = "freebsd"

    [[OpenSSL_CLI.download]]
    sha256 = "219d7c820253e80f034128a461059a2d493f9246406a3b504ffc784ed5fb84d8"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.8+0/OpenSSL_CLI.v3.5.8.aarch64-unknown-freebsd.tar.gz"
[[OpenSSL_CLI]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "db6d76e06e17508459828448300313a60d79237d"
libc = "glibc"
os = "linux"

    [[OpenSSL_CLI.download]]
    sha256 = "8c0ee6fce34d09772ab1dad37effec71ea8018d05b2462203d934bf38df25aa8"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.8+0/OpenSSL_CLI.v3.5.8.armv6l-linux-gnueabihf.tar.gz"
[[OpenSSL_CLI]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5289ab1636b6cdac6c2c6d63d1ee007908f8cdc7"
libc = "musl"
os = "linux"

    [[OpenSSL_CLI.download]]
    sha256 = "4446ad95bfbaad63122e540bd323cc27157ce7401a964149790a148db546ff07"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.8+0/OpenSSL_CLI.v3.5.8.armv6l-linux-musleabihf.tar.gz"
[[OpenSSL_CLI]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c9a6c4c6057e7aa808a7a59b0ad16ad9e516b380"
libc = "glibc"
os = "linux"

    [[OpenSSL_CLI.download]]
    sha256 = "b193b7a54380c8e97edf7a6efac2045c343512f8d450898c69c06547a30829a7"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.8+0/OpenSSL_CLI.v3.5.8.armv7l-linux-gnueabihf.tar.gz"
[[OpenSSL_CLI]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "210024cea334233ce3b26b24e04c85f283e5a4bb"
libc = "musl"
os = "linux"

    [[OpenSSL_CLI.download]]
    sha256 = "ca19685eb40cae85dfdaf778b42bb1907e1b27ba72877b387d26d4cd90e9bf19"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.8+0/OpenSSL_CLI.v3.5.8.armv7l-linux-musleabihf.tar.gz"
[[OpenSSL_CLI]]
arch = "i686"
git-tree-sha1 = "5b0c26fa8d1b4d6bc141a93f7b9ed58cbbf607be"
libc = "glibc"
os = "linux"

    [[OpenSSL_CLI.download]]
    sha256 = "25ed4c7cf3260330de23940658ce4b336b148f6c4620dee6ebc7025d94533a03"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.8+0/OpenSSL_CLI.v3.5.8.i686-linux-gnu.tar.gz"
[[OpenSSL_CLI]]
arch = "i686"
git-tree-sha1 = "a544ae875950bbd11e15cd1acc765d7a71d7f170"
libc = "musl"
os = "linux"

    [[OpenSSL_CLI.download]]
    sha256 = "e054e851150b05f4ff068240b94e04adf89a9d3d4d481856e772a51551f33b66"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.8+0/OpenSSL_CLI.v3.5.8.i686-linux-musl.tar.gz"
[[OpenSSL_CLI]]
arch = "i686"
git-tree-sha1 = "36d1d9847c3a760e9eb75fae7ab19b992c7000cd"
os = "windows"

    [[OpenSSL_CLI.download]]
    sha256 = "01109a7b7905f91d839ee74bbb83d9e4a91173a327bf8af8cdcad792442030b6"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.8+0/OpenSSL_CLI.v3.5.8.i686-w64-mingw32.tar.gz"
[[OpenSSL_CLI]]
arch = "powerpc64le"
git-tree-sha1 = "de6919d16998fb9919ce565e7d961606e90fb75e"
libc = "glibc"
os = "linux"

    [[OpenSSL_CLI.download]]
    sha256 = "a08a2265f2cc531a7f75b57fb0382e34cb446e2d02cf2dbe46520f8e9f3c6798"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.8+0/OpenSSL_CLI.v3.5.8.powerpc64le-linux-gnu.tar.gz"
[[OpenSSL_CLI]]
arch = "riscv64"
git-tree-sha1 = "c74b67e13c081291898ea25b5515a3670f78506f"
libc = "glibc"
os = "linux"

    [[OpenSSL_CLI.download]]
    sha256 = "46d1a3a5760b5cfa7e14fe4918986e5fbd9c7ac24710818f19da839c40e335ed"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.8+0/OpenSSL_CLI.v3.5.8.riscv64-linux-gnu.tar.gz"
[[OpenSSL_CLI]]
arch = "x86_64"
git-tree-sha1 = "67520296be37f9ca6c5fc81fed856d127dc22af7"
os = "macos"

    [[OpenSSL_CLI.download]]
    sha256 = "4a86429e45df1ca1579e40b00926e1c20eae0163be39513b5d1a689f425731bd"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.8+0/OpenSSL_CLI.v3.5.8.x86_64-apple-darwin.tar.gz"
[[OpenSSL_CLI]]
arch = "x86_64"
git-tree-sha1 = "df3446b07507b70df57ac61859692a3fdb87ebee"
libc = "glibc"
os = "linux"

    [[OpenSSL_CLI.download]]
    sha256 = "527373a987ca467e0f0058d96f31efea51abbaecef3961a5733ddeb1f491a358"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.8+0/OpenSSL_CLI.v3.5.8.x86_64-linux-gnu.tar.gz"
[[OpenSSL_CLI]]
arch = "x86_64"
git-tree-sha1 = "e96d88f0df1c90c10aef0414fea746cc1c3d1867"
libc = "musl"
os = "linux"

    [[OpenSSL_CLI.download]]
    sha256 = "e42e89945f28844973c25c2889f53854278565a953ab53a80e71e39c228c3778"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.8+0/OpenSSL_CLI.v3.5.8.x86_64-linux-musl.tar.gz"
[[OpenSSL_CLI]]
arch = "x86_64"
git-tree-sha1 = "69666b055aa37e70d6fdc6d0e27ac8d0291a26bc"
os = "freebsd"

    [[OpenSSL_CLI.download]]
    sha256 = "2fa5171c23a98f4c35e7e18a5e66c3aa45e14a01c82896d9f908b63082216a83"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.8+0/OpenSSL_CLI.v3.5.8.x86_64-unknown-freebsd.tar.gz"
[[OpenSSL_CLI]]
arch = "x86_64"
git-tree-sha1 = "a400d9dc993b1d5d2558e497b9cb02d63c624d0b"
os = "windows"

    [[OpenSSL_CLI.download]]
    sha256 = "d01f4218884bdc3b5a8cbacf8f27b9c28f4c2636e27b339c15bb72b4cb92a6cb"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.8+0/OpenSSL_CLI.v3.5.8.x86_64-w64-mingw32.tar.gz"
