[[OpenSSL_CLI]]
arch = "aarch64"
git-tree-sha1 = "58df6a1dac4470b4a7851347c41fb84a448b8ff1"
os = "macos"

    [[OpenSSL_CLI.download]]
    sha256 = "eff7a5d054e24266abb1de267aae7de6d6b13f6bc926b5cd982deefb8707ad8e"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.6+0/OpenSSL_CLI.v3.5.6.aarch64-apple-darwin.tar.gz"
[[OpenSSL_CLI]]
arch = "aarch64"
git-tree-sha1 = "57443f467a2251b8382834f4dda6fca9df2d85f4"
libc = "glibc"
os = "linux"

    [[OpenSSL_CLI.download]]
    sha256 = "2f71aa9f5dda68a67a1fb694558f76adbf4e8da1215b4517437330d1827313e4"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.6+0/OpenSSL_CLI.v3.5.6.aarch64-linux-gnu.tar.gz"
[[OpenSSL_CLI]]
arch = "aarch64"
git-tree-sha1 = "858a6b72c2af02b2ee54bfaf2bacdb0519d6eab8"
libc = "musl"
os = "linux"

    [[OpenSSL_CLI.download]]
    sha256 = "3d524bd49918d23143a493038a18f493ce697932cc9a0208f9043763a2ffa9f3"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.6+0/OpenSSL_CLI.v3.5.6.aarch64-linux-musl.tar.gz"
[[OpenSSL_CLI]]
arch = "aarch64"
git-tree-sha1 = "0fddc773da8f883ccb9449ef9598a9ecb11eb33f"
os = "freebsd"

    [[OpenSSL_CLI.download]]
    sha256 = "452e643a7b1b78584b5fd801b973b23910670278e7a447716d02894009da394e"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.6+0/OpenSSL_CLI.v3.5.6.aarch64-unknown-freebsd.tar.gz"
[[OpenSSL_CLI]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "336ad858cc926eeaa4ddd7e32b19b851aaa911be"
libc = "glibc"
os = "linux"

    [[OpenSSL_CLI.download]]
    sha256 = "41a6efe3d154e4b02f91e4daf8eb85bfc8cc9250c46f4fd3793fe8fa46e09870"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.6+0/OpenSSL_CLI.v3.5.6.armv6l-linux-gnueabihf.tar.gz"
[[OpenSSL_CLI]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0beab2962d2ec887a57ca05952d92ba37b4f6658"
libc = "musl"
os = "linux"

    [[OpenSSL_CLI.download]]
    sha256 = "bfb4ea524dd35aace8f2854c73b08776e319a83f48010729c7417d3607239c62"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.6+0/OpenSSL_CLI.v3.5.6.armv6l-linux-musleabihf.tar.gz"
[[OpenSSL_CLI]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b182c56a75df61e699ece4be350a1685176193b8"
libc = "glibc"
os = "linux"

    [[OpenSSL_CLI.download]]
    sha256 = "d8b1d2a146ba2f3f764e69e883cd015b6e72fe114f41678850c70c5c3e01cfdc"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.6+0/OpenSSL_CLI.v3.5.6.armv7l-linux-gnueabihf.tar.gz"
[[OpenSSL_CLI]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "35fea0145ff66658b0f79b0a770c6994424a08a0"
libc = "musl"
os = "linux"

    [[OpenSSL_CLI.download]]
    sha256 = "f50d682b4f5f29b47292643be919c3fee289b2b6a3a9a28a7c80787676c269f0"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.6+0/OpenSSL_CLI.v3.5.6.armv7l-linux-musleabihf.tar.gz"
[[OpenSSL_CLI]]
arch = "i686"
git-tree-sha1 = "623c53b37ead7a43f95261a8a506d54e7a191b93"
libc = "glibc"
os = "linux"

    [[OpenSSL_CLI.download]]
    sha256 = "e2d8aec6cf4af871938398bd94a90771eef7aeec912b06f8e181ae4fdf601843"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.6+0/OpenSSL_CLI.v3.5.6.i686-linux-gnu.tar.gz"
[[OpenSSL_CLI]]
arch = "i686"
git-tree-sha1 = "a8010f6aca8c7d0058893e8cb65c5e67aa11880e"
libc = "musl"
os = "linux"

    [[OpenSSL_CLI.download]]
    sha256 = "7376820463edc49ed90faf9cc0d17e9ac900155b9d1f398aa210926629738a3b"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.6+0/OpenSSL_CLI.v3.5.6.i686-linux-musl.tar.gz"
[[OpenSSL_CLI]]
arch = "i686"
git-tree-sha1 = "7856569dff15020d017bc27245faf84da9ca2751"
os = "windows"

    [[OpenSSL_CLI.download]]
    sha256 = "acc78b6b771c5dde32fcc51e978ffa3dc82fe322a396cb66e43b412b8042251a"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.6+0/OpenSSL_CLI.v3.5.6.i686-w64-mingw32.tar.gz"
[[OpenSSL_CLI]]
arch = "powerpc64le"
git-tree-sha1 = "e56457e5bfb4fdd0e8a0f0520459ab35f85dbe59"
libc = "glibc"
os = "linux"

    [[OpenSSL_CLI.download]]
    sha256 = "23b6e313c0174282749798d0af602352afc1196c3afba7d0dd6c5c9c681b92b3"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.6+0/OpenSSL_CLI.v3.5.6.powerpc64le-linux-gnu.tar.gz"
[[OpenSSL_CLI]]
arch = "riscv64"
git-tree-sha1 = "89340c163889b37244c8db9f435e19fb51cd597d"
libc = "glibc"
os = "linux"

    [[OpenSSL_CLI.download]]
    sha256 = "5c1b204b9c4b2d25f5b09cded98243c485343323f73ae5d70a511a05e07d89fd"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.6+0/OpenSSL_CLI.v3.5.6.riscv64-linux-gnu.tar.gz"
[[OpenSSL_CLI]]
arch = "x86_64"
git-tree-sha1 = "e2bfa6c710520eb83c3cab568decdd5b9ee5319f"
os = "macos"

    [[OpenSSL_CLI.download]]
    sha256 = "56363b0d5240fe9e165c74be0190227612b94e1e4ebd96ecb7fc34187616aee8"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.6+0/OpenSSL_CLI.v3.5.6.x86_64-apple-darwin.tar.gz"
[[OpenSSL_CLI]]
arch = "x86_64"
git-tree-sha1 = "774076d5842e6117e7ba43d5ebaa606522f6beeb"
libc = "glibc"
os = "linux"

    [[OpenSSL_CLI.download]]
    sha256 = "707a6abecb9eb42daadfab7db11c9d50f452438a31ccf5c6ee6064f7b5945025"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.6+0/OpenSSL_CLI.v3.5.6.x86_64-linux-gnu.tar.gz"
[[OpenSSL_CLI]]
arch = "x86_64"
git-tree-sha1 = "28c76c2ada434fd39c633a9e45d4c1066785a5ea"
libc = "musl"
os = "linux"

    [[OpenSSL_CLI.download]]
    sha256 = "2528437ce3f5cd988d4079a9f4de218bdfee55cffd43e2d21c85a1185828ee80"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.6+0/OpenSSL_CLI.v3.5.6.x86_64-linux-musl.tar.gz"
[[OpenSSL_CLI]]
arch = "x86_64"
git-tree-sha1 = "8a2b29f2ebc7e1e696f348f1038a3f2be6b490dd"
os = "freebsd"

    [[OpenSSL_CLI.download]]
    sha256 = "7434a91c03e04c38b10406c3d8f4ecde1d06e10255e8dce60478edcc2f2f16c6"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.6+0/OpenSSL_CLI.v3.5.6.x86_64-unknown-freebsd.tar.gz"
[[OpenSSL_CLI]]
arch = "x86_64"
git-tree-sha1 = "910388387ca4c3ac1896bf534cd3892be844183c"
os = "windows"

    [[OpenSSL_CLI.download]]
    sha256 = "a40bc560459b91b9c03348d835a21cf5e43220e3108237cafec5fa7783ac5463"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_CLI_jll.jl/releases/download/OpenSSL_CLI-v3.5.6+0/OpenSSL_CLI.v3.5.6.x86_64-w64-mingw32.tar.gz"
