# Autogenerated wrapper script for OpenSSL_CLI_jll for armv7l-linux-gnueabihf
export openssl

using OpenSSL_jll
JLLWrappers.@generate_wrapper_header("OpenSSL_CLI")
JLLWrappers.@declare_executable_product(openssl)
function __init__()
    JLLWrappers.@generate_init_header(OpenSSL_jll)
    JLLWrappers.@init_executable_product(
        openssl,
        "bin/openssl",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
